import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by Chitransh',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel='icon' href="/fav.ico"/>
      </head>
      <body className={inter.className}>
        <NavBar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
